In [1]:
import pandas as pd
import random
import numpy as np

In [2]:
df = pd.read_csv("Jobs.csv")

In [3]:
df.head()

,JobID,SubmitTime,WaitTime,RunTime,NProc,UsedCPUTime,UsedMemory,ReqNProcs,ReqTime,ReqMemory,...,JobStructureParams,UsedNetwork,UsedLocalDiskSpace,UsedResources,ReqPlatform,ReqNetwork,ReqLocalDiskSpace,ReqResources,VOID,ProjectID
0,1,1135130133,0,6,1,0.10,-1.0,-1,-1.0,-1.0,...,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,-1,-1,-1
1,2,1135130401,1,13,1,0.13,-1.0,-1,-1.0,-1.0,...,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,-1,-1,-1
2,3,1135130415,0,17,20,0.01,-1.0,-1,-1.0,-1.0,...,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,-1,-1,-1
3,4,1135130438,0,17,1,0.16,-1.0,-1,-1.0,-1.0,...,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,-1,-1,-1
4,5,1135130471,0,5,4,0.03,256.0,-1,-1.0,-1.0,...,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,-1,-1,-1

In [4]:
df.columns

Index(['JobID', 'SubmitTime', 'WaitTime', 'RunTime', 'NProc', 'UsedCPUTime',
       'UsedMemory', 'ReqNProcs', 'ReqTime', 'ReqMemory', 'Status', 'UserID',
       'GroupID', 'ExecutableID', 'QueueID', 'PartitionID', 'OrigSiteID',
       'LastRunSiteID', 'JobStructure', 'JobStructureParams', 'UsedNetwork',
       'UsedLocalDiskSpace', 'UsedResources', 'ReqPlatform', 'ReqNetwork',
       'ReqLocalDiskSpace', 'ReqResources', 'VOID', 'ProjectID'],
      dtype='object')

In [5]:
df = df.drop(df.columns[11:],1)
df = df.drop(df.columns[[0,7,8,9]],1)

In [6]:
df.head()

   SubmitTime  WaitTime  RunTime  NProc  UsedCPUTime  UsedMemory  Status
0  1135130133         0        6      1         0.10        -1.0       1
1  1135130401         1       13      1         0.13        -1.0       0
2  1135130415         0       17     20         0.01        -1.0       0
3  1135130438         0       17      1         0.16        -1.0       0
4  1135130471         0        5      4         0.03       256.0       1

In [7]:
df.count()

SubmitTime     1195242
WaitTime       1195242
RunTime        1195242
NProc          1195242
UsedCPUTime    1195242
UsedMemory     1195242
Status         1195242
dtype: int64

In [8]:
df = df[df['Status'] != 5]

In [9]:
df.count()

SubmitTime     1195242
WaitTime       1195242
RunTime        1195242
NProc          1195242
UsedCPUTime    1195242
UsedMemory     1195242
Status         1195242
dtype: int64

In [10]:
df.mean()

SubmitTime     1.157647e+09
WaitTime       2.866688e+04
RunTime        3.165430e+04
NProc          2.993179e+00
UsedCPUTime    2.075724e+04
UsedMemory     8.049621e+04
Status         1.606076e-01
dtype: float64

In [11]:
sb_mean = df[df['SubmitTime'] != -1]['SubmitTime'].mean()
wt_mean = df[df['WaitTime'] != -1]['WaitTime'].mean()
rt_mean = df[df['RunTime'] != -1]['RunTime'].mean()
NPr_mean = df[df['NProc'] != -1]['NProc'].mean()
cpuT_mean = df[df['UsedCPUTime'] != -1]['UsedCPUTime'].mean()
um_mean = df[df['UsedMemory'] != -1]['UsedMemory'].mean()
stt_mean = df[df['Status'] != -1]['Status'].mean()

In [12]:
# random for status = -1, keeping the mean
def random_status():
    if random.random() >= stt_mean:
        return 1
    return 0

In [13]:
# convert -1 to something meaningful
def convert_minus_one(df):
    df.loc[df['SubmitTime'] == -1,'SubmitTime'] = sb_mean
    df.loc[df['WaitTime'] == -1,'WaitTime'] = wt_mean
    df.loc[df['RunTime'] == -1,'RunTime'] = rt_mean
    df.loc[df['NProc'] == -1,'NProc'] = NPr_mean
    df.loc[df['UsedCPUTime'] == -1,'UsedCPUTime'] = cpuT_mean
    df.loc[df['UsedMemory'] == -1,'UsedMemory'] = um_mean
    df.loc[df['Status'] == -1,'Status'] = random_status()

In [14]:
convert_minus_one(df)

In [15]:
df.mean()

SubmitTime     1.157647e+09
WaitTime       3.098951e+04
RunTime        3.196426e+04
NProc          2.996717e+00
UsedCPUTime    2.271334e+04
UsedMemory     9.447847e+04
Status         1.606076e-01
dtype: float64

# check if funtion goes right
df1 = df[df['Status'] != 0]
df1[df1['Status'] != 1]

In [16]:
df['StartTime'] = df['SubmitTime'] + df['WaitTime']
df['EndTime'] = df['StartTime'] + df['RunTime']

In [17]:
df=df.drop(['SubmitTime','WaitTime','RunTime'],1)

In [18]:
df.head()

   NProc  UsedCPUTime    UsedMemory  Status     StartTime       EndTime
0    1.0         0.10  94478.471906       1  1.135130e+09  1.135130e+09
1    1.0         0.13  94478.471906       0  1.135130e+09  1.135130e+09
2   20.0         0.01  94478.471906       0  1.135130e+09  1.135130e+09
3    1.0         0.16  94478.471906       0  1.135130e+09  1.135130e+09
4    4.0         0.03    256.000000       1  1.135130e+09  1.135130e+09

In [19]:
df['Status'].value_counts()

0    1003277
1     191965
Name: Status, dtype: int64

In [20]:
start = df['StartTime'].min()

In [21]:
end = df['EndTime'].max()

In [22]:
(end - start)/60

563384.8417881688

In [29]:
# make time series data
def record_time_series(df, start, end, interval):
    prev = start
    cur = start + interval
    init_data = [[start/60, 0, 0]]
    columns = ['Time', 'CPU', 'Ram']
    time_df = pd.DataFrame(data = init_data, columns = columns)
    while(cur<=end):
        # take random number from normal sample
        x = random.uniform(prev, cur)
        # mask = (df['StartTime'] < x) & (df['EndTime'] >= x)
        new_df = df[df['StartTime'] >= prev]
        new_df = new_df[new_df['EndTime'] <= cur]
        sum1 = new_df['NProc'].sum()*60/interval
        sum2 = new_df['UsedMemory'].sum()*60/interval
        time_df = time_df.append({'Time':cur, 'CPU':sum1, 'Ram':sum2}, ignore_index=True)
        prev = cur
        cur = cur + interval
    return time_df

In [24]:
interval = 200

In [30]:
time_df = record_time_series(df, start, end, interval*60)

In [31]:
time_df

              Time     CPU           Ram
0     1.891884e+07   0.000  0.000000e+00
1     1.135142e+09   0.140  2.363242e+03
2     1.135154e+09   0.000  0.000000e+00
3     1.135166e+09   0.000  0.000000e+00
4     1.135178e+09   0.000  0.000000e+00
5     1.135190e+09   0.000  0.000000e+00
6     1.135202e+09   0.000  0.000000e+00
7     1.135214e+09   0.000  0.000000e+00
8     1.135226e+09   0.000  0.000000e+00
9     1.135238e+09   0.000  0.000000e+00
10    1.135250e+09   0.000  0.000000e+00
11    1.135262e+09   0.000  0.000000e+00
12    1.135274e+09   0.000  0.000000e+00
13    1.135286e+09   0.000  0.000000e+00
14    1.135298e+09   0.000  0.000000e+00
15    1.135310e+09   0.000  0.000000e+00
16    1.135322e+09   0.000  0.000000e+00
17    1.135334e+09   0.000  0.000000e+00
18    1.135346e+09   0.000  0.000000e+00
19    1.135358e+09   0.000  0.000000e+00
20    1.135370e+09   0.000  0.000000e+00
21    1.135382e+09   0.000  0.000000e+00
22    1.135394e+09   0.000  0.000000e+00
23    1.135406e+09   0.000  0.000000e+00
24    1.135418e+09   0.000  0.000000e+00
25    1.135430e+09   0.000  0.000000e+00
26    1.135442e+09   0.000  0.000000e+00
27    1.135454e+09   0.000  0.000000e+00
28    1.135466e+09   0.000  0.000000e+00
29    1.135478e+09   0.000  0.000000e+00
...            ...     ...           ...
2787  1.168574e+09   9.875  1.994618e+05
2788  1.168586e+09  18.490  3.581369e+05
2789  1.168598e+09   8.165  3.475991e+05
2790  1.168610e+09   6.745  3.481733e+05
2791  1.168622e+09   7.800  4.386448e+05
2792  1.168634e+09  16.630  5.128975e+05
2793  1.168646e+09  17.930  4.335676e+05
2794  1.168658e+09   4.475  5.258227e+05
2795  1.168670e+09   4.205  9.751973e+05
2796  1.168682e+09   1.985  5.285129e+05
2797  1.168694e+09   3.500  6.784090e+05
2798  1.168706e+09   5.080  3.506962e+05
2799  1.168718e+09   2.805  1.453333e+05
2800  1.168730e+09   7.170  1.275864e+06
2801  1.168742e+09   0.880  7.660935e+04
2802  1.168754e+09   6.290  1.107288e+05
2803  1.168766e+09   1.605  2.195664e+04
2804  1.168778e+09   2.240  1.984769e+05
2805  1.168790e+09   2.870  1.983047e+05
2806  1.168802e+09   2.840  2.657605e+05
2807  1.168814e+09   1.555  1.058190e+05
2808  1.168826e+09   1.040  1.696000e+04
2809  1.168838e+09   1.155  2.277126e+04
2810  1.168850e+09   1.980  1.122188e+05
2811  1.168862e+09   1.805  1.535822e+05
2812  1.168874e+09   2.350  1.742523e+05
2813  1.168886e+09   3.850  1.950950e+05
2814  1.168898e+09   3.355  3.085991e+05
2815  1.168910e+09   4.925  8.283374e+04
2816  1.168922e+09   0.320  2.834354e+03

[2817 rows x 3 columns]

In [32]:
time_df['CPU'].value_counts()

0.000000     513
0.005000      24
0.010000      14
0.160000      13
0.320000      10
0.080000       9
0.015000       9
0.120000       8
0.140000       8
0.020000       8
2.750000       7
0.245000       7
0.040000       7
0.420000       7
0.220000       7
0.014984       7
1.035000       7
0.185000       7
0.090000       7
1.155000       6
0.620000       6
0.029967       6
0.400000       6
0.685000       6
0.745000       6
0.115000       6
0.025000       6
0.030000       6
0.410000       6
0.870000       6
            ...
4.495000       1
9.920000       1
6.775000       1
12.290000      1
8.130000       1
5.980000       1
15.160000      1
12.325000      1
62.505000      1
13.770000      1
0.699984       1
4.260000       1
34.680000      1
3.645000       1
5.995000       1
2.285000       1
11.890000      1
9.015000       1
2.395000       1
0.384951       1
6.420000       1
5.660000       1
5.700000       1
5.955000       1
2.040000       1
11.260000      1
1.945000       1
11.195000      1
2.045000       1
11.280000      1
Name: CPU, Length: 1372, dtype: int64

In [33]:
time_df.to_csv('t10(200).csv')