In [1]:
import pandas as pd
import random
import numpy as np

In [2]:
df = pd.read_csv("Jobs.csv")

In [3]:
df.head()

,JobID,SubmitTime,WaitTime,RunTime,NProc,UsedCPUTime,UsedMemory,ReqNProcs,ReqTime,ReqMemory,...,JobStructureParams,UsedNetwork,UsedLocalDiskSpace,UsedResources,ReqPlatform,ReqNetwork,ReqLocalDiskSpace,ReqResources,VOID,ProjectID
0,1,1135130133,0,6,1,0.10,-1.0,-1,-1.0,-1.0,...,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,-1,-1,-1
1,2,1135130401,1,13,1,0.13,-1.0,-1,-1.0,-1.0,...,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,-1,-1,-1
2,3,1135130415,0,17,20,0.01,-1.0,-1,-1.0,-1.0,...,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,-1,-1,-1
3,4,1135130438,0,17,1,0.16,-1.0,-1,-1.0,-1.0,...,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,-1,-1,-1
4,5,1135130471,0,5,4,0.03,256.0,-1,-1.0,-1.0,...,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,-1,-1,-1

In [4]:
df.columns

Index(['JobID', 'SubmitTime', 'WaitTime', 'RunTime', 'NProc', 'UsedCPUTime',
       'UsedMemory', 'ReqNProcs', 'ReqTime', 'ReqMemory', 'Status', 'UserID',
       'GroupID', 'ExecutableID', 'QueueID', 'PartitionID', 'OrigSiteID',
       'LastRunSiteID', 'JobStructure', 'JobStructureParams', 'UsedNetwork',
       'UsedLocalDiskSpace', 'UsedResources', 'ReqPlatform', 'ReqNetwork',
       'ReqLocalDiskSpace', 'ReqResources', 'VOID', 'ProjectID'],
      dtype='object')

In [5]:
df = df.drop(df.columns[11:],1)
df = df.drop(df.columns[[0,7,8,9]],1)

In [6]:
df.head()

   SubmitTime  WaitTime  RunTime  NProc  UsedCPUTime  UsedMemory  Status
0  1135130133         0        6      1         0.10        -1.0       1
1  1135130401         1       13      1         0.13        -1.0       0
2  1135130415         0       17     20         0.01        -1.0       0
3  1135130438         0       17      1         0.16        -1.0       0
4  1135130471         0        5      4         0.03       256.0       1

In [7]:
df.count()

SubmitTime     1195242
WaitTime       1195242
RunTime        1195242
NProc          1195242
UsedCPUTime    1195242
UsedMemory     1195242
Status         1195242
dtype: int64

In [8]:
df = df[df['Status'] != 5]

In [9]:
df.count()

SubmitTime     1195242
WaitTime       1195242
RunTime        1195242
NProc          1195242
UsedCPUTime    1195242
UsedMemory     1195242
Status         1195242
dtype: int64

In [10]:
df.mean()

SubmitTime     1.157647e+09
WaitTime       2.866688e+04
RunTime        3.165430e+04
NProc          2.993179e+00
UsedCPUTime    2.075724e+04
UsedMemory     8.049621e+04
Status         1.606076e-01
dtype: float64

In [11]:
sb_mean = df[df['SubmitTime'] != -1]['SubmitTime'].mean()
wt_mean = df[df['WaitTime'] != -1]['WaitTime'].mean()
rt_mean = df[df['RunTime'] != -1]['RunTime'].mean()
NPr_mean = df[df['NProc'] != -1]['NProc'].mean()
cpuT_mean = df[df['UsedCPUTime'] != -1]['UsedCPUTime'].mean()
um_mean = df[df['UsedMemory'] != -1]['UsedMemory'].mean()
stt_mean = df[df['Status'] != -1]['Status'].mean()

In [12]:
# random for status = -1, keeping the mean
def random_status():
    if random.random() >= stt_mean:
        return 1
    return 0

In [13]:
# convert -1 to something meaningful
def convert_minus_one(df):
    df.loc[df['SubmitTime'] == -1,'SubmitTime'] = sb_mean
    df.loc[df['WaitTime'] == -1,'WaitTime'] = wt_mean
    df.loc[df['RunTime'] == -1,'RunTime'] = rt_mean
    df.loc[df['NProc'] == -1,'NProc'] = NPr_mean
    df.loc[df['UsedCPUTime'] == -1,'UsedCPUTime'] = cpuT_mean
    df.loc[df['UsedMemory'] == -1,'UsedMemory'] = um_mean
    df.loc[df['Status'] == -1,'Status'] = random_status()

In [14]:
convert_minus_one(df)

In [15]:
df.mean()

SubmitTime     1.157647e+09
WaitTime       3.098951e+04
RunTime        3.196426e+04
NProc          2.996717e+00
UsedCPUTime    2.271334e+04
UsedMemory     9.447847e+04
Status         1.606076e-01
dtype: float64

# check if funtion goes right
df1 = df[df['Status'] != 0]
df1[df1['Status'] != 1]

In [16]:
df['StartTime'] = df['SubmitTime'] + df['WaitTime']
df['EndTime'] = df['StartTime'] + df['RunTime']

In [17]:
df=df.drop(['SubmitTime','WaitTime','RunTime'],1)

In [18]:
df.head()

   NProc  UsedCPUTime    UsedMemory  Status     StartTime       EndTime
0    1.0         0.10  94478.471906       1  1.135130e+09  1.135130e+09
1    1.0         0.13  94478.471906       0  1.135130e+09  1.135130e+09
2   20.0         0.01  94478.471906       0  1.135130e+09  1.135130e+09
3    1.0         0.16  94478.471906       0  1.135130e+09  1.135130e+09
4    4.0         0.03    256.000000       1  1.135130e+09  1.135130e+09

In [19]:
df['NProc'].value_counts()

1.000000       1076464
4.000000         37492
8.000000         14373
2.000000         11824
7.000000         10372
16.000000        10217
32.000000         5004
64.000000         3857
20.000000         2556
10.000000         1657
5.000000          1473
12.000000         1336
3.000000          1249
2.996717          1058
6.000000           995
100.000000         985
60.000000          884
50.000000          857
11.000000          796
128.000000         711
30.000000          707
24.000000          591
40.000000          575
80.000000          571
9.000000           486
15.000000          445
25.000000          373
70.000000          337
28.000000          334
48.000000          298
                ...
2968.000000          1
1060.000000          1
177.000000           1
214.000000           1
2800.000000          1
1050.000000          1
1048.000000          1
215.000000           1
1032.000000          1
216.000000           1
168.000000           1
225.000000           1
228.000000           1
235.000000           1
769.000000           1
236.000000           1
245.000000           1
161.000000           1
1288.000000          1
155.000000           1
255.000000           1
850.000000           1
152.000000           1
267.000000           1
280.000000           1
1400.000000          1
292.000000           1
138.000000           1
210.000000           1
510.000000           1
Name: NProc, Length: 271, dtype: int64

In [20]:
start = df['StartTime'].min()

In [21]:
end = df['EndTime'].max()

In [22]:
df['BaseStart'] = df['StartTime'] - start
df['BaseEnd'] = df['EndTime'] - start

In [23]:
df.head(20)

,NProc,UsedCPUTime,UsedMemory,Status,StartTime,EndTime,BaseStart,BaseEnd
0,1.0,0.10,94478.471906,1,1.135130e+09,1.135130e+09,0.0,6.0
1,1.0,0.13,94478.471906,0,1.135130e+09,1.135130e+09,269.0,282.0
2,20.0,0.01,94478.471906,0,1.135130e+09,1.135130e+09,282.0,299.0
3,1.0,0.16,94478.471906,0,1.135130e+09,1.135130e+09,305.0,322.0
4,4.0,0.03,256.000000,1,1.135130e+09,1.135130e+09,338.0,343.0
5,1.0,0.13,94478.471906,0,1.135131e+09,1.135131e+09,702.0,718.0
6,1.0,0.11,94478.471906,0,1.138121e+09,1.138121e+09,2990460.0,2990466.0
7,1.0,0.10,1024.000000,0,1.138121e+09,1.138121e+09,2990470.0,2990475.0
8,1.0,0.13,1024.000000,0,1.138121e+09,1.138121e+09,2990531.0,2990536.0
9,80.0,0.00,94478.471906,1,1.138121e+09,1.138121e+09,2990805.0,2990811.0
10,80.0,1.69,51.000000,0,1.138121e+09,1.138121e+09,2990819.0,2990828.0
11,80.0,956.69,14694.000000,0,1.138121e+09,1.138122e+09,2990909.0,2991873.0
12,1.0,0.13,1024.000000,0,1.138121e+09,1.138121e+09,2990974.0,2990979.0
13,1.0,0.10,1024.000000,0,1.138121e+09,1.138121e+09,2991006.0,2991011.0
14,1.0,0.10,1024.000000,0,1.138121e+09,1.138121e+09,2991349.0,2991354.0
15,80.0,353.86,7756.000000,0,1.138123e+09,1.138124e+09,2993229.0,2993590.0
16,80.0,0.00,94478.471906,0,1.138125e+09,1.138126e+09,2994507.0,2995446.0
17,80.0,9.89,38.000000,1,1.138126e+09,1.138126e+09,2995471.0,2995487.0
18,80.0,9.11,38.000000,1,1.138126e+09,1.138126e+09,2995501.0,2995517.0
19,80.0,37.88,14412.000000,1,1.138126e+09,1.138126e+09,2995767.0,2995811.0

In [24]:
(end - start)/60

563384.8417881688

In [38]:
# make time series data
def record_time_series(df, start, end, interval):
    prev = start
    cur = start + interval
    init_data = [[start/60, 0, 0]]
    columns = ['Time', 'CPU', 'Ram']
    time_df = pd.DataFrame(data = init_data, columns = columns)
    while(cur<=end):
        # take random number from normal sample
        x = random.uniform(prev, cur)
        #filter out
        mask = (df['StartTime'] <= x) & (df['EndTime'] >= x)
        new_df = df[mask]
        #caculate
        sum1 = new_df['NProc'].sum()
        sum2 = new_df['UsedMemory'].sum()
        
        """
        print("Prev: ", prev, "Cur: ", cur)
        print("Value Count:\n", new_df['NProc'].value_counts())
        """

        time_df = time_df.append({'Time':cur/60, 'CPU':sum1, 'Ram':sum2}, ignore_index=True)
        prev = cur
        cur = cur + interval
    return time_df

In [34]:
interval = 50

In [39]:
time_df = record_time_series(df, start, end, interval*60)

In [36]:
time_df.head()

           Time  CPU  Ram
0  1.891884e+07  0.0  0.0
1  1.135133e+09  0.0  0.0
2  1.135136e+09  0.0  0.0
3  1.135139e+09  0.0  0.0
4  1.135142e+09  0.0  0.0

In [37]:
time_df['CPU'].value_counts()

0.000000       1509
2049.000000      58
864.000000       48
896.000000       48
53.000000        40
56.000000        40
922.000000       36
1.000000         34
221.000000       31
48.000000        30
925.000000       23
47.000000        23
52.000000        21
1068.000000      16
2098.817971      16
57.000000        15
2143.811404      15
865.000000       14
8.000000         13
1599.000000      13
907.000000       12
55.000000        12
54.000000        11
841.000000       11
1134.000000      11
1180.000000      11
1056.000000      11
2122.000000      11
44.000000        11
1235.804837      11
               ...
6512.000000       1
4880.000000       1
9296.000000       1
3756.000000       1
4817.000000       1
5609.000000       1
616.000000        1
6730.000000       1
6445.000000       1
7072.000000       1
5689.000000       1
5016.000000       1
4064.000000       1
2720.000000       1
2856.000000       1
1160.000000       1
572.000000        1
107.000000        1
2627.000000       1
520.000000        1
809.000000        1
2173.811404       1
6599.000000       1
5174.000000       1
6650.000000       1
7187.000000       1
3774.000000       1
3990.000000       1
2202.000000       1
480.000000        1
Name: CPU, Length: 4876, dtype: int64

In [30]:
time_df.to_csv('t10(200).csv')

# make function to run on Apache Spark

#slice time into parts
def slice_time(start, end, interval):
    slice = []
    while start < end:
        slice.append([start,start+interval])
        start += interval
    return slice

len(slice_time(start, end, 10*60))